import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="from-brand-primary to-blue-200 bg-brand-primary">
          <div className="max-w-screen-lg flex items-center p-8 mx-auto">
            <Link className="block w-fit h-fit" href="/">
              <Image
                alt="Sunsave logo"
                className="-mt-3 -ml-3"
                src="https://sunsave.energy/logo.svg"
                width={200}
                height={100}
              />
            </Link>
            <h1 className="ml-auto font-medium text-2xl text-slate-900">
              Pairing Exercise
            </h1>
          </div>
        </header>
        <main className="bg-gradient-to-b from-brand-primary to-brand-light to-60%">
          <div className="max-w-screen-lg mx-auto">{children}</div>
        </main>
      </body>
    </html>
  );
}
